apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expose-argocd-ui
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/learnandgrow459-ui/temp-to-delete.git
    targetRevision: HEAD
    path: expose-argocd-ui

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ServerSideApply=true